package com.utopia.gallery.model;

import java.io.Serializable;
import java.util.Date;

public class Works implements Serializable{
	
	private static final long serialVersionUID = 6603477834338392140L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.id
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.title
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.description
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.imageUrl
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    private String imageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.type
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.createDatetime
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    private Date createdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.updateDatetime
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    private Date updatedatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.reserve1
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.reserve2
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    private String reserve2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.id
     *
     * @return the value of works.id
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.id
     *
     * @param id the value for works.id
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.title
     *
     * @return the value of works.title
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.title
     *
     * @param title the value for works.title
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.description
     *
     * @return the value of works.description
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.description
     *
     * @param description the value for works.description
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.imageUrl
     *
     * @return the value of works.imageUrl
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.imageUrl
     *
     * @param imageurl the value for works.imageUrl
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.type
     *
     * @return the value of works.type
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.type
     *
     * @param type the value for works.type
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.createDatetime
     *
     * @return the value of works.createDatetime
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.createDatetime
     *
     * @param createdatetime the value for works.createDatetime
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.updateDatetime
     *
     * @return the value of works.updateDatetime
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public Date getUpdatedatetime() {
        return updatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.updateDatetime
     *
     * @param updatedatetime the value for works.updateDatetime
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public void setUpdatedatetime(Date updatedatetime) {
        this.updatedatetime = updatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.reserve1
     *
     * @return the value of works.reserve1
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.reserve1
     *
     * @param reserve1 the value for works.reserve1
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.reserve2
     *
     * @return the value of works.reserve2
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.reserve2
     *
     * @param reserve2 the value for works.reserve2
     *
     * @mbggenerated Fri Mar 20 13:26:36 CST 2015
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2;
    }
}